const sidebars = {
  /**
   * 笔记
   */
  // html: [{ type: 'autogenerated', dirName: 'notes/html' }],
  // css: [{ type: 'autogenerated', dirName: 'notes/css' }],
  // scss: [{ type: 'autogenerated', dirName: 'notes/scss' }],
  javascript: [{ type: 'autogenerated', dirName: 'notes/javascript' }],
  jquery: [{ type: 'autogenerated', dirName: 'notes/jquery' }],
  node: [{ type: 'autogenerated', dirName: 'notes/node' }],
  typescript: [{ type: 'autogenerated', dirName: 'notes/typescript' }],
  webpack: [{ type: 'autogenerated', dirName: 'notes/webpack' }],
  react: [{ type: 'autogenerated', dirName: 'notes/react' }],
  angular: [{ type: 'autogenerated', dirName: 'notes/angular' }],
  // next: [{ type: 'autogenerated', dirName: 'notes/next' }],
  // flutter: [{ type: 'autogenerated', dirName: 'notes/flutter' }],
  network: [{ type: 'autogenerated', dirName: 'notes/network' }],
  /**
   * 博客
   */
  blog: [{ type: 'autogenerated', dirName: 'blogs' }],
  /**
   * DevOps
   */
  devops: [{ type: 'autogenerated', dirName: 'devops' }],
  /**
   * Wiki
   */
  wiki: [{ type: 'autogenerated', dirName: 'wiki' }],
};

module.exports = sidebars;
